M48
; DRILL file {KiCad 9.0.6} date 2026-09-21T15:13:40-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-21T15:13:40-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.050
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.800
%
G90
G05
T1
X180.222Y-87.87
X180.222Y-102.87
T2
X184.222Y-87.87
X184.222Y-102.87
M30
