M48
; DRILL file {KiCad 9.0.6} date 2026-09-21T15:04:44-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-21T15:04:44-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.050
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.800
%
G90
G05
T1
X174.507Y-88.004
X174.507Y-103.004
T2
X178.507Y-88.004
X178.507Y-103.004
M30
